# =========================================================================##
# Read input variables to run TAMSAT-ALERT for Maize yield meteorological
# risk assessment using GLAM crop model.
# ==========================================================================##
# 1.  filename: File containing the JULES forcing file
# 2.  Station name
# 3.  stat: Statistical method to use for probability (normal or ecdf)
# 4.  wth_path: file path of the weather data files (.wth)
# 5.  glam_command: GLAM command line
# 6.  soiltex: soil texture (USDA classification: one of the 12 classes)
# 7.  lat: Latitude
# 8.  lon: Longitude
# 9.  datastartyear: Data start year
# 10. dataendyear: Data end year
# 11. climastartyear: Climatological start year
# 12. climaendyear: Climatological end year
# 13. forecastyear: TAMSAT-ALERT Forecast year
# 14. forecastmonth: TAMSAT-ALERT Forecast month
# 15. forecastday: TAMSAT-ALERT Forecast date
# 16. weights: Seasonal forecast [below average , average, above average]
#             as fraction
# 17. weight_var: weighting variable seasonal total rainfall (0)
#                and average seasonal temperature (1)
# 18. wf_year: Weighting Forecast year (This year is normally
#             similar to TAMSAT-ALERT Forecast year)
# 19. wf_month: Weighting Forecast month (1 - 12)
# 20. wf_day: Weighting Forecast day (1 - 31)
# 21. w_leadtime: Weighting Forecast lead time (1 - 365)
# 22. climafile: climatological values of the metric forecasted
#               (e.g. climatological yield)
# 23. forecastfile: ensembles of the forecasted metric (e.g. ensembles of yield)
# 24. weightfile: weighting file generated by weighting script
#                (rainfall or temperature depending on wight_var above)
# =============================================================================#
import warning
from config import *
# =============================================================================#
sta_name = "tamale"
stat = "normal"
wth_path = ".\\config\\maize_ghana\\ascii_input\\wth\\"
glam_command = ".\glam .\config\maize_ghana\maize_east_africa.glam SET 0.19"
soiltex = "sandy loam"
lat = 9.55
lon = -0.85
weights = [0.333, 0.334, 0.333]
weight_var = 0
wf_year = 2002
wf_month = 7
wf_day = 1
w_leadtime = 90

# ==============================================================================#
# Variable imported from config.py (main TAMSAT-ALERT v1.0 general code)
# these variables are changed in the config.py
# ==============================================================================#
filename = filename
climafile = climatological_metric_file
forecastfile = ensemble_metric_file
weightfile = forecast_metric_file
datastartyear = datastartyear
dataendyear = dataendyear
climastartyear = climstartyear
climaendyear = climendyear
forecastyear = init_year
forecastmonth = init_month
forecastday = init_day

# ================================================================================================##
# DO NOT CHANGE ANYTHING BELOW THIS LINE.
# The function below will check if variable values are given correctly.
# ================================================================================================##
warning.check_input_var(filename, sta_name, stat, wth_path, glam_command, soiltex, lat, lon,
                        datastartyear, dataendyear, climastartyear, climaendyear, forecastyear,
                        forecastmonth, forecastday, weights, weight_var, wf_year, wf_month,
                        wf_day, w_leadtime)
# ================================================================================================##
